const CONFIG=window.CAMPUS_ROUTE_CONFIG||{};
const configured=Boolean(CONFIG.supabaseUrl&&CONFIG.supabaseAnonKey);
const db=configured?window.supabase.createClient(CONFIG.supabaseUrl,CONFIG.supabaseAnonKey):null;
const state={session:null,members:[],colleges:[],assignments:[],editing:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const today=new Date().toISOString().slice(0,10);
const demo={members:[{id:'m1',full_name:'Sample Team Member',email:'sample@capgemini.com',city:'Pune',unified_grade:'B2',category:'FTE',can_travel:true}],colleges:[{id:'c1',college_name:'Sample Engineering College',college_group:'Sample Group',college_city:'Nagpur',college_state:'Maharashtra',college_zone:'West',assessment_date:today,interview_date:null,nearest_airport:'Dr. Babasaheb Ambedkar International Airport',airport_distance_km:12,nearest_station:'Nagpur Junction',station_distance_km:8}],assignments:[{id:'a1',member_id:'m1',college_id:'c1',assignment_date:today,status:'Assessment',notes:''}]};
function iso(v){return v?String(v).slice(0,10):''} function fmt(v){if(!v)return '—';return new Date(v+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})} function initials(n){return n.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()} function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
async function init(){['focusDate','rosterDate','plannerFrom'].forEach(id=>$('#'+id).value=today);const d=new Date();d.setDate(d.getDate()+14);$('#plannerTo').value=d.toISOString().slice(0,10);bind();if(!configured){$('#setupBanner').classList.remove('hidden');Object.assign(state,demo);renderAll();return}await refreshSession();await loadData();}
function bind(){ $$('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));['focusDate','rosterDate'].forEach(id=>$('#'+id).onchange=renderAll);['rosterSearch','collegeSearch'].forEach(id=>$('#'+id).oninput=renderAll);['travelFilter','zoneFilter','collegeStatusFilter','plannerFrom','plannerTo','plannerBase'].forEach(id=>$('#'+id).onchange=renderAll);$('#signInBtn').onclick=signInAction;$('#signInForm').onsubmit=sendMagicLink;$('#addMemberBtn').onclick=()=>openEditor('member');$('#addCollegeBtn').onclick=()=>openEditor('college');$('#addAssignmentBtn').onclick=()=>openEditor('assignment');$('#exportRosterBtn').onclick=exportRoster;$('#exportCollegesBtn').onclick=exportColleges;$('#exportPlanBtn').onclick=exportPlan;}
function showView(name){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$$('.view').forEach(x=>x.classList.toggle('active',x.id===name+'View'));}
async function refreshSession(){const {data}=await db.auth.getSession();state.session=data.session;db.auth.onAuthStateChange((_e,s)=>{state.session=s;renderAuth()});renderAuth()}
function renderAuth(){const email=state.session?.user?.email;$('#signInBtn').textContent=email?'Sign out':'Sign in';$('#syncState').textContent=email?'Synced as '+email:'View only';const allowed=email?.toLowerCase().endsWith('@'+CONFIG.allowedDomain);$$('#addMemberBtn,#addCollegeBtn,#addAssignmentBtn').forEach(b=>b.disabled=!allowed)}
async function signInAction(){if(state.session){await db.auth.signOut();toast('Signed out');return}if(!configured){toast('Add Supabase settings first');return}$('#signInDialog').showModal()}
async function sendMagicLink(e){e.preventDefault();const email=$('#signInEmail').value.trim().toLowerCase();if(!email.endsWith('@'+CONFIG.allowedDomain)){$('#signInMessage').textContent='Use an @'+CONFIG.allowedDomain+' email address.';return}const {error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:location.href.split('#')[0]}});$('#signInMessage').textContent=error?error.message:'Check your inbox for the secure sign-in link.'}
async function loadData(){const [m,c,a]=await Promise.all([db.from('team_members').select('*').order('full_name'),db.from('colleges').select('*').order('college_name'),db.from('assignments').select('*').order('assignment_date')]);if(m.error||c.error||a.error){$('#setupBanner').classList.remove('hidden');$('#setupBanner span').textContent='The database is not ready yet. Run supabase/migrations/001_initial.sql, then import data.xlsx with the included script.';Object.assign(state,demo)}else{state.members=m.data;state.colleges=c.data;state.assignments=a.data}renderAll()}
function renderAll(){renderAuth();populateFilters();renderOverview();renderRoster();renderColleges();renderPlanner()}
function populateFilters(){const fill=(el,vals,label)=>{const current=el.value;el.innerHTML='<option value="all">'+label+'</option>'+vals.map(v=>'<option>'+esc(v)+'</option>').join('');el.value=[...el.options].some(o=>o.value===current)?current:'all'};fill($('#zoneFilter'),[...new Set(state.colleges.map(x=>x.college_zone).filter(Boolean))].sort(),'All zones');fill($('#plannerBase'),[...new Set(state.members.map(x=>x.city).filter(Boolean))].sort(),'All bases')}
function assignmentFor(memberId,date){return state.assignments.filter(a=>a.member_id===memberId&&iso(a.assignment_date)===date)}
function collegeName(id){return state.colleges.find(c=>c.id===id)?.college_name||'Travel / other duty'}
function renderOverview(){const date=$('#focusDate').value||today;const todays=state.assignments.filter(a=>iso(a.assignment_date)===date);const duplicates=new Set(todays.filter((a,i,arr)=>arr.findIndex(x=>x.member_id===a.member_id)!==i).map(a=>a.member_id));$('#metricMembers').textContent=state.members.length;$('#metricTravellers').textContent=state.members.filter(m=>m.can_travel).length+' available to travel';$('#metricColleges').textContent=state.colleges.length;$('#metricScheduled').textContent=state.colleges.filter(c=>c.assessment_date||c.interview_date).length+' scheduled';$('#metricAssignments').textContent=todays.length;$('#metricConflicts').textContent=duplicates.size;const rows=todays.slice(0,8).map(a=>{const m=state.members.find(x=>x.id===a.member_id)||{};return `<div class="deployment-row"><span class="avatar">${initials(m.full_name||'?')}</span><div><strong>${esc(m.full_name)}</strong><small>${esc(collegeName(a.college_id))} · ${esc(a.status)}</small></div><span class="badge ${duplicates.has(a.member_id)?'danger':''}">${duplicates.has(a.member_id)?'Conflict':esc(m.city||'')}</span></div>`}).join('');$('#dayDeployment').innerHTML=rows||'<div class="empty">No assignments on '+fmt(date)+'</div>';const total=Math.max(state.colleges.length,1),air=state.colleges.filter(c=>c.nearest_airport).length,rail=state.colleges.filter(c=>c.nearest_station).length;$('#readiness').innerHTML=progress('Airport mapped',air,total)+progress('Railway mapped',rail,total)+progress('Both distances captured',state.colleges.filter(c=>c.airport_distance_km!=null&&c.station_distance_km!=null).length,total)}
function progress(label,value,total){const pct=Math.round(value/total*100);return `<div><div class="progress-label"><span>${label}</span><strong>${pct}%</strong></div><div class="progress"><i style="width:${pct}%"></i></div><small>${value} of ${total} colleges</small></div>`}
function renderRoster(){const q=$('#rosterSearch').value.toLowerCase(),date=$('#rosterDate').value,tf=$('#travelFilter').value;const rows=state.members.filter(m=>(tf==='all'||(m.can_travel?'Yes':'No')===tf)&&[m.full_name,m.city,...assignmentFor(m.id,date).map(a=>collegeName(a.college_id))].join(' ').toLowerCase().includes(q)).map(m=>{const ass=assignmentFor(m.id,date);const status=ass.length?ass.map(a=>esc(a.status+': '+collegeName(a.college_id))).join('<br>'):'Available';return `<tr><td><strong>${esc(m.full_name)}</strong><span class="subtext">${esc(m.email)}</span></td><td>${esc(m.city)}</td><td>${esc(m.unified_grade||'—')}</td><td>${esc(m.category||'—')}</td><td><span class="badge ${m.can_travel?'':'warn'}">${m.can_travel?'Yes':'No'}</span></td><td>${status}</td><td><button class="row-action" onclick="openEditor('member','${m.id}')">Edit</button></td></tr>`}).join('');$('#rosterBody').innerHTML=rows||'<tr><td colspan="7" class="empty">No matching team members</td></tr>'}
function renderColleges(){const q=$('#collegeSearch').value.toLowerCase(),zone=$('#zoneFilter').value,sf=$('#collegeStatusFilter').value;const rows=state.colleges.filter(c=>(zone==='all'||c.college_zone===zone)&&(!q||[c.college_name,c.college_group,c.college_city,c.college_state].join(' ').toLowerCase().includes(q))&&(sf==='all'||(sf==='scheduled'&&(c.assessment_date||c.interview_date))||(sf==='missing'&&(!c.nearest_airport||!c.nearest_station)))).map(c=>`<tr><td><strong>${esc(c.college_name)}</strong><span class="subtext">${esc(c.college_group||'')}</span></td><td>${esc(c.college_city)}<span class="subtext">${esc(c.college_state)} · ${esc(c.college_zone||'')}</span></td><td>${fmt(iso(c.assessment_date))}</td><td>${fmt(iso(c.interview_date))}</td><td>${esc(c.nearest_airport||'—')}<span class="subtext">${c.airport_distance_km??'—'} km</span></td><td>${esc(c.nearest_station||'—')}<span class="subtext">${c.station_distance_km??'—'} km</span></td><td><button class="row-action" onclick="openEditor('college','${c.id}')">Edit</button></td></tr>`).join('');$('#collegeBody').innerHTML=rows||'<tr><td colspan="7" class="empty">No matching colleges</td></tr>'}
function renderPlanner(){const from=$('#plannerFrom').value,to=$('#plannerTo').value,base=$('#plannerBase').value;const items=state.assignments.filter(a=>{const m=state.members.find(x=>x.id===a.member_id);const d=iso(a.assignment_date);return d>=from&&d<=to&&(base==='all'||m?.city===base)});const dates=[...new Set(items.map(a=>iso(a.assignment_date)))].sort();$('#routeTimeline').innerHTML=dates.map(date=>`<div class="route-day"><div class="route-date">${fmt(date)}</div><div class="route-cards">${items.filter(a=>iso(a.assignment_date)===date).map(a=>{const m=state.members.find(x=>x.id===a.member_id)||{},c=state.colleges.find(x=>x.id===a.college_id)||{};return `<article class="route-card"><div><strong>${esc(c.college_name||a.status)}</strong><small>${esc(c.college_city||'')} ${c.college_state?'· '+esc(c.college_state):''}</small></div><div><strong>${esc(m.full_name||'Unassigned')}</strong><small>Base: ${esc(m.city||'—')}</small></div><div><strong>${esc(c.nearest_airport||'Airport not mapped')}</strong><small>${c.airport_distance_km??'—'} km · Rail ${c.station_distance_km??'—'} km</small></div><button class="row-action" onclick="openEditor('assignment','${a.id}')">Edit</button></article>`}).join('')}</div></div>`).join('')||'<div class="empty panel">No planned assignments in this date range</div>'}
const schemas={member:[['full_name','Full name','text'],['email','Email','email'],['city','Base city','text'],['unified_grade','Unified grade','text'],['category','Category','text'],['can_travel','Available to travel','checkbox']],college:[['college_name','College name','text'],['college_group','College group','text'],['college_city','City','text'],['college_state','State','text'],['college_zone','Zone','text'],['assessment_date','Assessment date','date'],['interview_date','Interview date','date'],['nearest_airport','Nearest airport','text'],['airport_distance_km','Airport distance (km)','number'],['nearest_station','Nearest railway station','text'],['station_distance_km','Station distance (km)','number']],assignment:[['member_id','Team member','member'],['college_id','College','college'],['assignment_date','Date','date'],['status','Status','select'],['notes','Notes','text']]};
function openEditor(type,id){if(configured&&!state.session){toast('Sign in to edit');return}const list=type==='member'?state.members:type==='college'?state.colleges:state.assignments;const rec=list.find(x=>x.id===id)||{};state.editing={type,id};$('#dialogTitle').textContent=(id?'Edit ':'Add ')+({member:'team member',college:'college',assignment:'assignment'}[type]);$('#dialogFields').innerHTML=schemas[type].map(([key,label,kind])=>field(key,label,kind,rec[key])).join('');$('#editorForm').onsubmit=saveEditor;$('#editorDialog').showModal()}
function field(key,label,kind,value){if(kind==='checkbox')return `<label class="full"><span>${label}</span><input name="${key}" type="checkbox" ${value?'checked':''}></label>`;if(kind==='member')return `<label>${label}<select name="${key}" required><option value="">Select</option>${state.members.map(x=>`<option value="${x.id}" ${x.id===value?'selected':''}>${esc(x.full_name)} · ${esc(x.city)}</option>`).join('')}</select></label>`;if(kind==='college')return `<label class="full">${label}<select name="${key}"><option value="">Travel / no college</option>${state.colleges.map(x=>`<option value="${x.id}" ${x.id===value?'selected':''}>${esc(x.college_name)}</option>`).join('')}</select></label>`;if(kind==='select')return `<label>${label}<select name="${key}">${['Assessment','Interview','Travel','Return','Unavailable'].map(x=>`<option ${x===value?'selected':''}>${x}</option>`).join('')}</select></label>`;return `<label class="${key==='college_name'||key==='full_name'?'full':''}">${label}<input name="${key}" type="${kind}" value="${esc(kind==='date'?iso(value):value??'')}" ${['full_name','email','college_name','assignment_date'].includes(key)?'required':''}></label>`}
async function saveEditor(e){e.preventDefault();const fd=new FormData(e.target),{type,id}=state.editing,data=Object.fromEntries(fd.entries());if(type==='member')data.can_travel=Boolean(e.target.elements.can_travel.checked);['airport_distance_km','station_distance_km'].forEach(k=>{if(k in data)data[k]=data[k]===''?null:Number(data[k])});const table=type==='member'?'team_members':type==='college'?'colleges':'assignments';if(!configured){data.id=id||crypto.randomUUID();const list=type==='member'?state.members:type==='college'?state.colleges:state.assignments;const i=list.findIndex(x=>x.id===id);i>=0?list.splice(i,1,data):list.push(data);$('#editorDialog').close();renderAll();toast('Saved in local preview');return}const query=id?db.from(table).update(data).eq('id',id):db.from(table).insert(data);const {error}=await query;if(error){toast(error.message);return}$('#editorDialog').close();await loadData();toast('Saved')}
function csv(rows,cols,name){const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';const out=[cols.map(x=>quote(x[1])).join(','),...rows.map(r=>cols.map(x=>quote(r[x[0]])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([out],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportRoster(){const date=$('#rosterDate').value;csv(state.members.map(m=>({...m,date_status:assignmentFor(m.id,date).map(a=>a.status+': '+collegeName(a.college_id)).join(' | ')||'Available'})),[['full_name','Full Name'],['email','Email ID'],['city','Base'],['unified_grade','Grade'],['category','Category'],['can_travel','Can Travel'],['date_status',date+' Status']],'team-roster-'+date+'.csv')}
function exportColleges(){csv(state.colleges,[['college_name','College'],['college_group','College Group'],['college_city','City'],['college_state','State'],['college_zone','Zone'],['assessment_date','Assessment Date'],['interview_date','Interview Date'],['nearest_airport','Nearest Airport'],['airport_distance_km','Airport Distance KM'],['nearest_station','Nearest Station'],['station_distance_km','Station Distance KM']],'college-travel-master.csv')}
function exportPlan(){const rows=state.assignments.map(a=>{const m=state.members.find(x=>x.id===a.member_id)||{},c=state.colleges.find(x=>x.id===a.college_id)||{};return{date:iso(a.assignment_date),status:a.status,name:m.full_name,base:m.city,college:c.college_name,city:c.college_city,airport:c.nearest_airport,airport_km:c.airport_distance_km,station:c.nearest_station,station_km:c.station_distance_km,notes:a.notes}});csv(rows,[['date','Date'],['status','Status'],['name','Person'],['base','Base'],['college','College'],['city','College City'],['airport','Nearest Airport'],['airport_km','Airport KM'],['station','Nearest Station'],['station_km','Station KM'],['notes','Notes']],'travel-plan.csv')}
init();
